### ISSUE TITLE
Ready to test

### ISSUE THREAD

**Issue by earth08** [Thunderbird2086/ha-custom-component-dumbir#1]
Dear,
Please mention config, so that i can test and reply here.
Thank you very much to see you again for this lovely mod

**Comment by earth08** [comment]
Dear,
I tried with the last config in feature added version of vasillis
one problem which i found is i cant turn on my ac,
after turning on my ac i can control with dumbir,

**Comment by earth08** [comment]
error
2019-05-07 18:31:09 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit/type_thermostats.py", line 250, in update_state
    if isinstance(target_temp, float) and current_temp > target_temp:
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by Thunderbird2086** [comment]
Oh, the `homekit` is `Apple HomeKit`? 
From the error message,  `current_temp` is `NoneType`.  However, I'm not sure where it came from such as `current target temperature` or `actual temperature` from temperature sensor.  
I will take a look at `HomeKit` component, tomorrow. 

By the way, you can use same IR data file (*.ini) under the same directory from @vpnmaster's old project.  I will update README.md too.

**Comment by earth08** [comment]
Dear,
I have configure this component the same way we did last.
but i am unable to put on my ac.
i can turn it off, make it swing, but cant turn it on.

**Comment by earth08** [comment]
Dear,
Dont worry about the error above as i have turned off my homekit integration and the error has gone.
Please check why airconditioner doesnt turn on.
thanks in adv.
