### ISSUE TITLE
Not working after upgrade to 0.96.0

### ISSUE THREAD

**Issue by earth08** [Thunderbird2086/ha-custom-component-dumbir#4]
DearAllen,
Dumbir component stopped working after upgrading homeassistant to 0.96.0.
Please check.
Thanks

**Comment by Thunderbird2086** [comment]
I have realized it today and am working on it.  
Thanks for reporting, @earth08

**Comment by Thunderbird2086** [comment]
@earth08 
please try [quick fix](https://github.com/Thunderbird2086/ha-custom-component-dumbir/blob/quick-fix-for-ha-0.96.0/dumbir/climate.py).
It's working fine for me though.

**Comment by earth08** [comment]
@Thunderbird2086 ,
It does work,
but am facing same problem,
can put my ac on with dumbir.
Please guide

**Comment by Thunderbird2086** [comment]
@earth08 , can you elaborate what your problem is? 
If you were talking about 'Turn On', then it's not possible at this moment as `SUPPORT_ON_OFF` option has been removed from `component/climate.py` from HA.

**Comment by earth08** [comment]
Dear, 
It’s working,
I can put On and Off my AC with smartir.
But I like this dumbir as it provides me lots of other feature.
So I asked here.
Thanks

**Comment by Thunderbird2086** [comment]
I am going to close this issue as I released 0.1.1

**Comment by Thunderbird2086** [comment]
I am going to close this issue as 0.1.1 has been released.
